### ISSUE TITLE
RHSM config refreshes on every run when server_port is set

### ISSUE THREAD

**Issue by ekingme** [waveclaw/puppet-subscription_manager#22] opened 2016-05-26 14:28 UTC
We are setting server port to 8443 in one data center and 443 in the other.  When we specify these values (via hiera), hosts refresh their subscription manager configuration on every puppet run.  If we don't specify the value at all and use default (443), the puppet run does not make changes (as expected).

Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]/server_port	server_port changed '8443' to '8443'

module v2.0.0 from the forge
puppet-3.8.4-1.el6.noarch
subscription-manager-1.13.12-1.el6.x86_64

**Comment by waveclaw** [comment] 2016-06-02 21:25
Thank you for your report. 

I will try to reproduce this so I can work on a solution.  

From your information the rhsm_config native type appears to not be detecting that you already have set that value.  

The 1.12.2 work was dedicated to stamping out this particular problem as it affected the path settings for the certificate.  

This particular case may require a re-write of the rhsm_config native type.

**Comment by Ramorous** [comment] 2016-06-09 13:33
I found the same issue. Found none of the facter libs were working. I did some rework and subsequently got rhsm_identity to work properly.

```
require 'facter'
Facter.add(:rhsm_identity) do
    setcode do
      value = nil
      RHSMbin = "/usr/sbin/subscription-manager"
      if File.exist?(RHSMbin)
        output = Facter::Util::Resolution.exec( "#{RHSMbin} identity" )
        split_output = output.split("\n")
        split_output.each do |line|
          if line =~ /.* identity(?: is)?: (\S{8}\-\S{4}\-\S{4}\-\S{4}\-\S{12}).*/
            value = $1
          end
        end
      end
      value
    end
end
```

I'm new to Ruby, but this is how I got it to work. If you update let me know, I would greatly appreciate it.

**Comment by Ramorous** [comment] 2016-06-09 13:43
Added begin and exceptions to it...

```
require 'facter'
Facter.add(:rhsm_identity) do
  setcode do
    value = nil
    begin
      rhsm_bin = "/usr/sbin/subscription-manager"
      if File.exist?(rhsm_bin)
        output = Facter::Util::Resolution.exec( "#{rhsm_bin} identity" )
        split_output = output.split("\n")
        split_output.each do |line|
          if line =~ /.* identity(?: is)?: (\S{8}\-\S{4}\-\S{4}\-\S{4}\-\S{12}).*/
            value = $1
          end
        end
      end
    rescue Exception => e
      Facter.debug("#{e.backtrace[0]}: #{$!}.")
    end
    value
  end
end
```

**Comment by ekingme** [comment] 2016-06-09 20:06
We updated our fact to what Ramorous has recommended and our hosts are still making the port change in the RHSM config.

**Comment by Ramorous** [comment] 2016-06-09 20:32
Apologies, I misread the issue you were having with one of my own. Which I found kept doing that because of the rshm_identity fact.

**Comment by waveclaw** [comment] 2016-06-10 02:21
The problem with Ramorous' approach is that it is confusing the role of the module with the Facter fact itself.  The module-based fact exists not just to contain the complex code but also to provide a surface area for testing.

Facter is already being told to limit the value to systems where subscription-manager's file exists where the fact is being created lower in the file.

Duplicating this into the module just causes all unit tests to fail if the system running the tests does not  have subscription-manager installed.  For instance, you can no longer run rSpec tests for that value on a Mac or Ubuntu running computer since the lookup for the file '/usr/sbin/subscription-manager' will always fail.

@Ramorous, please open a request with your issue if you still have one. I can try to examine the problem you are having seperate from the lack of idempotentcy in rhsm_config.  Thank you for providing the code you did. However, the code you provided for the reasons I mentioned cannot be used in this specific case.

**Comment by waveclaw** [comment] 2016-07-13 07:30
@ekingme  the sync issue appears to have been resolved by dropping all the custom ensure and insync? mechanisms.  This means dropping support for Puppet bellow 3.3.  Testing in a CentOS 6 and 7 VMs show no repeat of the custom settings.  

I am still pending a clean Puppet 2016 installation to do testing with a pure Puppet 4 environment before releasing this.

**Comment by waveclaw** [comment] 2016-08-28 23:43
Updating this to the 2.2 release.

**Closed by waveclaw** 2016-08-28 23:43 UTC
Labels: bug
