### ISSUE TITLE
Subscription-manger runs on every run (v2.2.1)

### ISSUE THREAD

**Issue by dzeleski** [waveclaw/puppet-subscription_manager#39] opened 2017-01-30 15:08 UTC
Hi,

I have this module installed as well as its dependencies via code manager:
```
mod 'waveclaw/subscription_manager', '2.2.1'
mod 'waveclaw/facter_cacheable', '0.1.0'
mod 'puppetlabs/transition', '0.1.0'
mod 'adrien/boolean', '1.0.1'
```

We wrap your module with our own like such:
```
class <modulename>::components::satellite(
  String $url         = undef,
  String $org         = undef,
  String $ca_name     = undef,
  String $ca_source   = undef,
  ) {
  # https://forge.puppetlabs.com/waveclaw/subscription_manager

  $rhel_version = $facts['os']['release']['major']

  # If the client evi fact does not exist fail to UAT
  if $facts['client_environment'] != undef {
    $satellite_envi = $facts['client_environment']['satellite_envi']
  }
  else {
    $satellite_envi = 'UAT'
  }

  package { 'subscription-manager':
    ensure => 'present'
  }

  package { 'katello-ca-consumer-latest.noarch.rpm':
    ensure          => 'present',
    provider        => 'rpm',
    install_options => [ '--replacefiles' ],
    # Options
    name            => $ca_name,
    source          => $ca_source,
  }

  rhsm_register { $url:
    ensure        => 'present',
    #autosubscribe => true,
    force         => true,
    # Options
    org           => $org,
    activationkey => "RHEL ${rhel_version} ${satellite_envi}",
  }

  rhsm_repo { "rhel-${rhel_version}-server-rh-common-rpms":
    ensure => 'present',
  }

  rhsm_repo {"rhel-${rhel_version}-server-satellite-tools-6.2-rpms":
    ensure => 'present',
  }

  package { 'katello-agent':
    ensure => 'latest',
  }
}
```

Every single puppet run I see the factor facts run for subscription manager, as well as the module itself running a repo list. This is currently causing longer then normal puppet runs due to these facts running. Its very possible that I am doing something wrong but at this point I cant figure out why its occurring. The master has been restarted after installing these modules as well.

Any help would be much appreciated.

**Comment by pgassmann** [comment] 2017-02-06 15:16
check `puppet resource rhsm_register`, does this match your settings? do you have a proxy configured? See #40

**Comment by dzeleski** [comment] 2017-02-06 16:49
@pgassmann It looks like it is missing settings:
```
[root@<REMOVED>]# puppet resource rhsm_register
rhsm_register { '<REMOVED>':
  ensure   => 'present',
  identity => 'bae0616d-3<TRUNCATED>,
}
```

```
  rhsm_register { $url:
    ensure        => 'present',
    #autosubscribe => true,
    force         => true,
    # Options
    org           => $org,
    activationkey => "RHEL ${rhel_version} ${satellite_envi}",
  }
```

**Comment by pgassmann** [comment] 2017-02-06 17:13
The options are not shown with `puppet resource rhsm_register`. That is correct. The problem is, that you are using `$url` instead of just the hostname `<REMOVED>.domain.lan` in your rhsm_register.

You should probably not use rhsm_register directly, but use the class parameters insead, like in the example in the README:

```
  class { 'subscription_manager':
     server_hostname => 'satellite.example.com',
     org             => 'My_Company_Org',
     activationkey   => '1234-key',
     autosubscribe   => true,
     servicelevel    => 'STANDARD',
     config_hash     => {
       server_prefix          => '/rhsm',
       rhsm_baseurl           => "https://satellite.example.com/pulp/repos",
       rhsm_repo_ca_cert      => '%(ca_cert_dir)s/katello-server-ca.pem',
     },
     service_name    =>'rhsmcertd',
     force           => true,
  }
```

**Comment by dzeleski** [comment] 2017-02-06 18:00
Thats just a shitty var name that unfortunately got left over and re used. The data in hiera is just the FQDN of the satellite server. 

Otherwise I can definitely move over using the class resource to call it. I think we may have used this module before that documentation was there? I see what we are currently doing lower down in the types and providers section. Not sure but I will test that out and report back.

Thanks for the help!

**Comment by waveclaw** [comment] 2017-02-20 05:29
> Every single puppet run I see the factor facts run for subscription manager, as well as the module itself running a repo list. 

This is a problem with caching of the facts.  The repository, pool and identity are not going to change frequently. There is no reason for Puppet to always request them from the original server.  Identity checks are quick and low cost.  The search for available, disabled and enabled packages repositories and RedHat Network Subscription pools are expensive.  I attempted to write caching support to reduce the frequency, with the target of no more than daily and tunable by the site.

However, changes to facts in Puppet invalidated the caching support every time I implement something that worked.    At this point, to support Puppet 4 the facts will re-written completely.  I have been studying the problem but currently have no effective solution.

I'm keeping this problem open while I continue to research.

**Comment by waveclaw** [comment] 2017-02-20 06:14
As for rhsm_register, with `force => true` the type will re-register every single Puppet run. 

The subscription_manager module goes through great pains to avoid having to use rhsm_register with `force => true`.  However, this is unavoidable for certain combinations of new registrations, old registrations and broken or unclean un-registrations.

If you want to use rhsm_register yourself, you will have to re-create the logic inside the module to prevent re-runs of rhsm_register with `force => true`.

This is because the force option indicates if you do not care what the current registration state is. With `force => true` you want Puppet to ignore the state of the registration and run subscription-manager again.

This is the opposite of how Puppet resources are supposed to work.  They should compare the desired state of the system with the existing state and only issue corrections as needed.  The force option says to skip this check and just do the registration no matter what the state of the registration is at this time.

RedHat Satellite 6.1.2 and later have actual code to avoid the obvious problem using force causes.  That problem is multiple registrations of the same host.

I can suggest looking at the `rhsm_identity` fact or creating your own facts based on the validity of the registration.  These may involve expensive processes on your Foreman, Katello or Satellite 6 server.

**Comment by dzeleski** [comment] 2017-02-20 06:27
@waveclaw Appreciate the response. On your first message that makes sense and that does seem to be what im currently seeing as well. I have a dedicated lab for testing, if you need assistance testing or messing around with things let me know id be glad to help.

For your second response...

We have had a terrible time with sat 6, currently running 6.2.7, registrations breaking, sat crashing, rpm stores corrupting, etc. So I had to set that to keep the systems registered properly. The registrations have just become stable for us so im planning on removing that very soon in production, its been turned off in our lab for a few weeks now. 

Ill get that rolled out to staging tomorrow and hopefully get it out to everyone mid week.

**Comment by waveclaw** [comment] 2017-03-29 03:58
Closing for end of 2.x series.

**Closed by waveclaw** 2017-03-29 03:58 UTC
